version: '3.8'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
    depends_on:
      - database
    env_file:
      - .env
    ports:
      - '3000:3000'

volumes:
  postgres_data:
